w5d1-master/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:edit, :update, :destroy] do
    resources :comments, only: :create
  end

  resources :goals, except: :index do
    resources :comments, only: :create
  end


end

w5d1-master/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :commentable_id, :commentable_type, :author_id, presence: true

  belongs_to :commentable, polymorphic: true

end

w5d1-master/app/models/goal.rb
class Goal < ActiveRecord::Base

  validates :title, presence: true
  validates :private, inclusion: [true, false]

  belongs_to :user

  has_many :comments, as: :commentable


end

w5d1-master/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  has_many :comments, as: :commentable

  has_many :goals

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password
    @password
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end


end

w5d1-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @ce ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

w5d1-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if params[:user_id]
      @user = User.find(params[:user_id])
      @comment = @user.comments.new(comment_params)
    elsif params[:goal_id]
      @goal = Goal.find(params[:goal_id])
      @comment = @goal.comments.new(comment_params)
    end
    @comment.author_id = current_user.id

    unless @comment.save
      flash[:error] = "Comment cannot be blank"
    end

    if @user
      redirect_to user_url(@user)
    else
      redirect_to goal_url(@goal)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end


end

w5d1-master/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :require_owner, only: [:edit, :update, :destroy]
  before_action :check_privacy, only: :show

  def show
    @goal = Goal.find(params[:id])
    @comments = @goal.comments
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    @goal.private ||= false

    if @goal.save
      redirect_to goal_url(@goal)
    else
      render :new
    end

  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.private = false unless params[:goal][:private]

    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      render :edit
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to users_url
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :description, :private)
  end

  def require_owner
    goal = Goal.find(params[:id])

    unless logged_in? && goal.user_id == current_user.id
      redirect_to users_url
    end
  end

  def check_privacy
    goal = Goal.find(params[:id])

    if goal.private && current_user.id != goal.user_id
      redirect_to user_url(goal.user_id)
    end

  end
end

w5d1-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:username], params[:password])

    if @user && login!(@user)
      redirect_to users_url
    else
      flash[:error] = "invalid login"
      render :new
    end
  end

  def destroy
    logout!
    redirect_to users_url
  end
end

w5d1-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to users_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals
    @comments = @user.comments
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

end

w5d1-master/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token

    <<-HTML.html_safe
    <input type="hidden"
           name="authenticity_token"
           value="#{ form_authenticity_token }">
    HTML

  end

end

w5d1-master/app/helpers/goals_helper.rb
module GoalsHelper
end

w5d1-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1-master/app/helpers/users_helper.rb
module UsersHelper
end

w5d1-master/app/views/comments/_form.html.erb
<% action_url = @user ?
  user_comments_url(params[:id]) : goal_comments_url(params[:id]) %>

<%= flash[:error] %>
<br>

<% if logged_in? %>
  <form action="<%= action_url %>" method="post">
    <%= auth_token %>
    <label for="comment">Add a Comment</label>
    <textarea id="content" name="comment[content]" rows="8" cols="40"></textarea>
    <button>Submit Comment</button>
  </form>
<% end %>

w5d1-master/app/views/comments/_show.html.erb
<% @comments.each do |comm| %>
<%= comm.content %>
<br>
<% end %>

w5d1-master/app/views/goals/_form.html.erb
<% action_url = goal.persisted? ? goal_url(goal) : goals_url %>
<% method = goal.persisted? ? 'patch' : "post" %>
<% button_text = goal.persisted? ? "Update Goal" : "Create Goal" %>


<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>
    title
  <input type="text" name="goal[title]" value="<%= goal.title %>">
  </label>

  <label>
    description
  <textarea name="goal[description]"><%= goal.description %></textarea>
  </label>

  <label>private
    <input
      type="checkbox"
      name="goal[private]"
      value='true' <%= 'checked' if goal.private %>
    >
  </label>

  <button><%= button_text %></button>

</form>

w5d1-master/app/views/goals/edit.html.erb
<%= @goal.errors.full_messages %>
<h1> Edit Goal </h1>
<%= render 'form', goal: @goal %>
<form action="<%= goal_url(@goal)%>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <button>Delete Goal</button>
</form>

w5d1-master/app/views/goals/new.html.erb
<%= @goal.errors.full_messages %>

<h1>Create a New Goal</h1>

<%= render 'form', goal: @goal %>

w5d1-master/app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>
<p><%= @goal.description %></p>

<% if logged_in? && current_user.id == @goal.user_id %>
  <a href="<%= edit_goal_url(@goal) %>">Edit Goal</a>
<% end %>
<br>

<%= render "comments/show", comments: @comments %>
<br>

<%= render "comments/form" %>

w5d1-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <%= current_user.username %>
  <form action="<%= session_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="delete">
    <button>Log Out</button>
  </form>
<% else %>
  <a href="<%= new_session_url %>">User Sign In</a>
<% end %>


<%= yield %>

</body>
</html>