reddit-master/config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'

  resources :subs, except: :destroy do
    resources :posts, only: [:new]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]

  resources :posts, except: [:index, :destroy, :new] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]


end

reddit-master/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :moderator, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs
  )

  has_many :postings, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :postings, source: :post, inverse_of: :subs


  def moderator_name
    moderator.username
  end

  def moderator_id
    moderator.id
  end
end

reddit-master/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit, :update]
  before_action :require_logged_in, except: [:show, :index]

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    sub = Sub.find(params[:id])
    unless sub.moderator_id == current_user.id
      redirect_to sub_url(sub)
    end
  end
end

reddit-master/app/helpers/subs_helper.rb
module SubsHelper
end

reddit-master/app/views/subs/_edit_sub.html.erb
<% if current_user_id == sub.moderator_id %>

You are the moderator:
<a href="<%= edit_sub_url(sub) %>">Edit this sub</a>

<% else %>
  <h4>moderated by <%= @sub.moderator_name.downcase %>  </h4>
<% end %>

reddit-master/app/views/subs/_form.html.erb
<% if sub.persisted? %>
  <form action="<%= sub_url(sub) %>" method="post">
  <%= hidden_patch %>
<% else %>
  <form action="<%= subs_url %>" method="post">
<% end %>

    <%= auth_token %>
  <label>
    Title:
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <br>

  <label>Description:
    <textarea name="sub[description]" ><%= sub.description %></textarea>
  </label>
  <br>

  <button>Submit</button>
</form>

reddit-master/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render 'shared/errors', object: @sub %>

<%= render 'form', sub: @sub %>

reddit-master/app/views/subs/index.html.erb
<h1>Subs</h1>


<table>
  <thead>
    <th> Title </th>
    <th> Moderator </th>
    <th> Description </th>
  </thead>

  <tbody>
    <% @subs.each do |subforum| %>
      <tr>
        <td> <a href="<%= sub_url(subforum) %>"> <%= subforum.title %> </a></td>
        <td align=center> <%= subforum.moderator_name %> </td>
        <td> <%= subforum.description %> </td>
      </tr>
    <% end %>
  </tbody>


</table>

<a href="<%= new_sub_url %>">Create a Sub</a>

reddit-master/app/views/subs/new.html.erb
<h1>New sub</h1>

<%= render 'shared/errors', object: @sub %>


<%= render 'form', sub: @sub %>

reddit-master/app/views/subs/show.html.erb
<h1><%= @sub.title.titleize %></h1>

<aside>
  <pre><em><%= @sub.description || "no description yet" %></em></pre>
</aside>

<main>
  <% @posts.each do |post| %>
    <a href="<%= post_url(post) %>" ><%= post.title %></a>
    <em>(<%= post.author_name  %>)</em>
    <blockquote>
      <%= post.content %>
    </blockquote>
  <% end %>
</main>

<a href="<%= new_sub_post_url(@sub) %>">New post</a>
<br>
<%= render "edit_sub", sub: @sub %>